[package]
name = "oddsketch"
version = "0.1.0"
authors = ["Harry Barber <hlbarber93@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3.0"
rand = "0.7.2"

[[bench]]
name = "oddsketch"
harness = false
