[package]
name = "oddsketch"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3.4"
rand = "0.8.3"

[[bench]]
name = "oddsketch"
harness = false
