[package]
name = "oddsketch"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3.3"
rand = "0.8.1"

[[bench]]
name = "oddsketch"
harness = false
